### ISSUE TITLE
S3 API Credentials

### ISSUE THREAD

**Issue by bitdivision** [ibm-public-cos/crs-beta-docs#1]
Is there any documentation available on how to generate an Access key / Secret Key required for access to the S3 API? I can't find any information on this and the bluemix dashboard doesn't seem to allow you to do it.

**Comment by nglange** [comment]
Sorry for the delayed response - I'll fix my email settings so that I don't miss anything.   :-1: 

Documentation for getting credentials from the UI are found here: https://ibm-public-cos.github.io/crs-docs/crs-control-credentials

Note that there are three different object storage services.  The S3 API is used to access the Cross Region service, which is available under Infrastructure in the Bluemix Catalog, rather than the OpenStack Swift based object storage available under Services.  I know this is confusing, and we are working on making this more intuitive - we are beginning to implement the new IBM Cloud Object Storage system across Bluemix but at the moment it is a standalone service that requires an upgraded account.  Here's some more info: https://ibm-public-cos.github.io/crs-docs/crs-other-offerings.html

Feel free to follow up if you want some further clarification.
